### ISSUE TITLE
Pattern `napi_bigint` not covered

### ISSUE THREAD

**Issue by KillerCodeMonkey** [napi-rs/napi-rs#276] opened 2020-11-02 08:24 UTC
I am really new to rust and all that universe.

i tried to install napi and so on, but i get:

```
error[E0004]: non-exhaustive patterns: `napi_bigint` not covered
   --> ../.cargo/registry/src/github.com-1ecc6299db9ec823/napi-0.5.1/src/js_values/value_type.rs:46:11
    |
46  |     match value {
    |           ^^^^^ pattern `napi_bigint` not covered
    | 
   ::: ../target/debug/build/napi-sys-c52f7ba1a7f9b699/out/bindings.rs:358:5
    |
358 |     napi_bigint = 9,
    |     ----------- not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `napi_sys::napi_valuetype`
```

Thanks :)

**Comment by Brooooooklyn** [comment] 2020-11-02 08:56
Seems like you are using non-stable NodeJS version. Please upgrade to latest LTS NodeJS and try again

**Comment by KillerCodeMonkey** [comment] 2020-11-02 09:04
```sh
▶ cargo test
   Compiling napi v0.5.1
error[E0004]: non-exhaustive patterns: `napi_bigint` not covered
   --> ../.cargo/registry/src/github.com-1ecc6299db9ec823/napi-0.5.1/src/js_values/value_type.rs:46:11
    |
46  |     match value {
    |           ^^^^^ pattern `napi_bigint` not covered
    | 
   ::: ../target/debug/build/napi-sys-c52f7ba1a7f9b699/out/bindings.rs:358:5
    |
358 |     napi_bigint = 9,
    |     ----------- not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `napi_sys::napi_valuetype`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0004`.
error: could not compile `napi`.

To learn more, run the command again with --verbose.
```

```sh
▶ node -v
v14.15.0
```

No luck :(.

To describe my problem more:
I have a workspace rust project, where i have two libs:

1. the rust part
2. the node wrapper (will use first one later)

even`cargo install` fails with

```sh
▶ cargo install
error: no packages found with binaries or examples
```

my .toml for the node part:

```toml
[package]
name = "read-media-node"
version = "0.1.0"
authors = ["Bengt Weiße <bengtler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "0.5"
napi-derive = "0.5"

[build-dependencies]
napi-build = "0.2"
```

**Comment by adumbidiot** [comment] 2020-11-03 01:58
How was nodejs installed?

**Comment by KillerCodeMonkey** [comment] 2020-11-03 06:08
Via nvm

Nathaniel Daniel <notifications@github.com> schrieb am Di., 3. Nov. 2020,
02:58:

**Comment by phinat29** [comment] 2020-11-04 09:03
I have same with nidejs v12.13

**Comment by Azorlogh** [comment] 2020-11-04 09:40
It seems to be because the #[cfg(napi6)] isn't validated. I have no idea why though, I couldn't figure out what's supposed to set it true in the first place.

**Comment by Brooooooklyn** [comment] 2020-11-04 09:42
This issue is expected fix by https://github.com/napi-rs/napi-rs/pull/271#issuecomment-720011729

**Comment by KillerCodeMonkey** [comment] 2020-11-04 09:43
thanks for letting us know.

**Comment by Brooooooklyn** [comment] 2020-11-04 09:48
The root cause of this problem is in some `NodeJS` version, `process.versions.napi` was not set to the right value which expected to match with the `NAPI_VERSION` in `node_api.h`.

It may be temporary fixed by using `node@12.13+` versions, which was fully tested.

**Comment by adumbidiot** [comment] 2020-11-04 09:54
> It may be temporary fixed by using `node@12.13+` versions, which was fully tested.

If the above error is the only error that occurs while compiling, you might be able to work-around by using the master branch. I believe #278 works around this by throwing an error when it encounters types it can't understand.

**Comment by adumbidiot** [comment] 2020-11-04 09:54
Also, `cargo install` is for installing binaries. Maybe you meant `cargo update` or `cargo build`?

**Comment by Brooooooklyn** [comment] 2020-11-10 10:10
Should be closed in https://github.com/napi-rs/napi-rs/pull/290

**Closed by Brooooooklyn** 2020-11-10 10:10 UTC
Labels: bug

**Comment by KillerCodeMonkey** [comment] 2020-11-24 14:04
@Brooooooklyn is there already a new release with the fix?

**Comment by Brooooooklyn** [comment] 2020-11-24 15:34
@KillerCodeMonkey Fixed in master branch but not released yet
