### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _SecRandomCopyBytes on m1 mac

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#654] opened 2021-07-16 08:30 UTC
I got this error report via slack.

## Environment

```
big sur 11.4
node version: v14.17.0
```

## Note

npm emits a warning, complaining that the node version is different between scripts and npm.

```
npm WARN lifecycle The node binary used for scripts is /var/folders/gy/kq4zjn8s0ljf9sfjyyh_nj640000gn/T/yarn--1626422621576-0.3039819202739642/node but npm is using /Users/<redacted>/.nvm/versions/node/v14.17
.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

```

But same result even if `--scripts-prepend-node-path` is used.

Is `MACOSX_DEPLOYMENT_TARGET ` required for m1 builds?

**Comment by Brooooooklyn** [comment] 2021-07-19 04:32
I don't have m1 device :( So I can't reproduce this issue for now. As I know, the `MACOSX_DEPLOYMENT_TARGET` will not effect the m1 builds.

**Comment by kdy1** [comment] 2021-07-19 04:38
I see. Then I'll try to fix this by searching.

**Comment by Brooooooklyn** [comment] 2021-07-20 06:42
Fixed by https://github.com/swc-project/swc/pull/1939

**Closed** 2021-07-20 06:42 UTC
