### ISSUE TITLE
Bug naming a function

### ISSUE THREAD

**Issue by LimitR** [napi-rs/napi-rs#1062] opened 2022-02-05 18:20 UTC
If i named function with snake_case style, function not working. 
Version: 
```
napi = {version="2.0.3", features=["async"]}
napi-derive = "2.0.7"
```

Errors can watch after compiling

Example:
```rust
#[napi]
fn my_func(){
    //...
}
// But it's working correct
#[napi]
fn myFunc(){
    //...
}
```

**Comment by antoniomuso** [comment] 2022-03-06 18:14
Here seems the issue is the conversion to camelCase of napi, we have that `my_func` is converted to `myFunc` then one hides the other. 
I think the issue can be fixed by forcing snake cases for napi functions. WDYT?

**Comment by forehalo** [comment] 2022-03-08 05:55
@antoniomuso 
I think it's better not force users to use `snake_case` naming convention even it's what rust community recommanded, and instead we should have users to do the selection, witch is also why we've provided with the attribute option `js_name` besides converting all js symbols to `camelCase`.

if you meet that function hiding problem you could use that `js_name` option to avoid it, like:

```rust
#[napi]
fn my_func(){
    //...
}

#[napi(js_name="myAnotherFunc"]
fn myFunc(){
    //...
}
```

**Comment by yisibl** [comment] 2022-03-08 06:10
The default in wasm-bindgen is to use the `snake_case `. Given that napi-rs will also support WASM in the future, I suggest that the default value of `js_name` should be changed to `snake_case`.

See also: https://github.com/yisibl/resvg-js/blob/8dfadca59d49f4f286cf2b1c94e54b7b9fa298e1/src/lib.rs#L116-L117

**Comment by yisibl** [comment] 2022-03-08 06:20
Implicit conversion to camelCase can cause a lot of confusion for users.

**Comment by antoniomuso** [comment] 2022-03-08 06:50
> @antoniomuso 
> I think it's better not force users to use `snake_case` naming convention even it's what rust community recommanded, and instead we should have users to do the selection, witch is also why we've provided with the attribute option `js_name` besides converting all js symbols to `camelCase`.
> 
> if you meet that function hiding problem you could use that `js_name` option to avoid it, like:
> 
> ```rust
> #[napi]
> fn my_func(){
>     //...
> }
> 
> // or `#[napi(js_name="my_another_func"]` if you or your team prefer
> #[napi(js_name="myAnotherFunc"]
> fn myFunc(){
>     //...
> }
> ```


But this may be confused, the conversion in camel case can create this situation. From my point of view, forcing the snake_case for napi functions avoids these kinds of bugs. If you want to use your custom case, you have to use the js_value

**Comment by yisibl** [comment] 2022-03-08 06:57
There is no need to force it, just change the default value.


What a function looks like in Rust is what a function looks like in JS. If you need a hump, then use:

```rust
#[napi(js_name="myFunc"]
// The default js function is my_func
fn my_func(){
    //...
}
```

**Comment by antoniomuso** [comment] 2022-03-08 07:25
> @joaomoreno There is no need to force it, just change the default value.
> 
> What a function looks like in Rust is what a function looks like in JS. If you need a hump, then use:
> 
> ```rust
> #[napi(js_name="myFunc"]
> // The default js function is my_func
> fn my_func(){
>     //...
> }
> ```

Yeah, you fix the issue, but you are reducing the developer experience in this way. The auto conversion in camel case is good for me, in 90% of cases you want to convert it in camel case.

**Comment by forehalo** [comment] 2022-03-08 09:25
@yisibl 
there is no need to keep the name convention same with wasm_bindgen, we provided fully generated `.d.ts` for letting user know what are generated by default and that's also well noted in the docs. 

As far as I can see is the coming wasm support will be the way like generating intermediate code in wasm_bindgen style by napi macro, which means we might ship wasm_bindgen code like `#[wasm_bindgen(js_name = toString)]` as well for regard of most JS users who follow camelCase by default the most

**Comment by yisibl** [comment] 2022-03-08 12:59
`.d.ts` can only solve the problem for third-party users to a certain extent.

The main problem is that we need to be more friendly to the contributors of the library, and implicit conversions can be baffling to contributors, as my colleague encountered with napi-rs when I was working with him. Because traditional Rust developers don't know that napi-rs and wasm-bindgen have completely different results on js_name, we can't just consider JS users.

Translated with www.DeepL.com/Translator (free version)

**Comment by timfish** [comment] 2022-03-08 13:11
> There is no need to force it, just change the default value.

Changing the default naming convention would be a breaking change. ie. you'd need to release napi v3

**Comment by Brooooooklyn** [comment] 2022-03-08 13:48
Maybe we can provide a new `features` flag to persist the raw `function names` without breaking existing APIs and behaviors.

**Comment by forehalo** [comment] 2022-03-08 14:01
I like the idea of providing a new feature `codegen/snake_case` that napi will output all exports as they are

**Comment by forehalo** [comment] 2022-03-08 14:03
whoops, should not be close yet, sorry for my miss operating

**Comment by forehalo** [comment] 2022-03-08 14:09
we could make it as a stradand so all those codegen preferences should be able to opt in with features like `codegen/type` or `codegen/camelCase` and such

**Comment by antoniomuso** [comment] 2022-03-08 14:47
It seems a good approach

**Comment by yisibl** [comment] 2022-03-09 11:42
New `features` +1

**Closed** 2023-06-08 09:25 UTC
